name: Build and Deploy Assistant Services

on:
  push:
    branches:
      - internal-assistant-main
      - external-assistant-main
      - insight-assistant-main
      - common-service-main

jobs:
  internal-assistant-main:
    if: github.ref == 'refs/heads/internal-assistant-main'
    runs-on: ubuntu-latest
    steps:
      - name: Test internal
        run: |
          echo "✅ internal-assistant-main branch push detected - test internal 성공"

  external-assistant-main:
    if: github.ref == 'refs/heads/external-assistant-main'
    runs-on: ubuntu-latest
    steps:
      - name: Test external
        run: |
          echo "✅ external-assistant-main branch push detected - test external 성공"

  insight-assistant-main:
    if: github.ref == 'refs/heads/insight-assistant-main'
    runs-on: ubuntu-latest
    steps:
      - name: Test insight
        run: |
          echo "✅ insight-assistant-main branch push detected - test insight 성공"

  common-service-main:
    if: github.ref == 'refs/heads/common-service-main'
    runs-on: ubuntu-latest
    steps:
      - name: Test common
        run: |
          echo "✅ common-service-main branch push detected - test common 성공"
